---
apiVersion: v1
kind: Pod
metadata:
  name: dep-search-pod
  labels:
    app: dep-search-app
spec:
  containers:
    - name: dep-search
      image: image
      env:
      - name: OBJECT_STORAGE_CREDENTIALS
        value: "credentials"
      volumeMounts:
      - name: bosque-db
        mountPath: /data/bosque-db
      #ports:
      #  - containerPort: 80
  volumes:
  - name: bosque-db
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: dep-search-service
spec:
  type: NodePort
  selector:
    app: dep-search-app
  ports:
  - protocol: TCP
    port: 45678
    targetPort: 45678
    nodePort: 30001
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dep-search
spec:
  replicas: 0
  template:
    metadata:
      name: dep-search-pod
      labels:
        app: dep-search-app
    spec:
      containers:
        - name: dep-search
          image: image
          env:
          - name: OBJECT_STORAGE_CREDENTIALS
            value: "credentials"
          volumeMounts:
          - name: bosque-db
            mountPath: /data/bosque-db
          #ports:
          #  - containerPort: 80
      volumes:
      - name: bosque-db
        emptyDir: {}
